
FROM php:8.1-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y zip curl unzip libpq-dev zlib1g-dev libpng-dev libjpeg-dev libfreetype6-dev

# Install PHP extensions
# RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install gd pdo pdo_pgsql pgsql
# Get Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy existing application directory
COPY . .

# Install Laravel dependencies
RUN composer install

RUN php artisan key:generate

# Expose port 8000 and start php-fpm server
CMD php artisan migrate && php artisan db:seed --class=UserSeeder && php artisan serve --host=0.0.0.0 --port=8000

